io.txt:
    title:  Time Series for {}

    # columns [name, unit, description]
    columns:
        time: 
            [Time, '', Time stamp]
            # [sidt, h  Sidereal time in seconds since midnight]
        value: 
            [x, '', Time series value]
        sigma:   
            [σ, '', Standard deviation uncertainty of value]
        outlier: 
            [oflag, '', Outlier flag]

    precision:  3   # significant figures


ts:
    # time series plot parametes
    plotting:
        timescale:    s
        start:        null

        figure:
            size:           [14, 8]
            margins:
                top:        0.81
                bottom:     0.1
                left:       0.065
                right:      0.94

        axes:
            plims:          [-0.1, 99.99]
            labels:
                # TODO: axes_label_position: (left right center <>^)
                x:
                    top:        Time (UTC)
                    bottom:     Δt (s)
                    pad:        -17.5
                    ticks:
                        rotation:   45
                y:
                    left:       Relative Flux

            twinx:        null  # Top x-axis display format

        line:
            ls:             '-'
            ms:             0

        errorbar:
            fmt:            o
            ms:             2.5
            mec:            none
            capsize:        0
            elinewidth:     0.5
        
        spans:
            label:          filtered
            alpha:          0.2
            color:          r
        
        hist:
            bins:           50
            alpha:          0.75
            # color:        b
            orientation:    horizontal
        
        legend:
            loc:            upper right  # TODO: option for no legend
            fancybox:       True
            framealpha:     0.25
            numpoints:      1
            markerscale:    3

spectral:
    io.txt:
        title:  Spectral density estimate for {}

        # columns [name, unit, description]
        columns:
            time: 
                [Frq, 'Hz', Frequency]
            value: 
                [Power, '', Power]

        precision:  3   # significant figures