# ---------------------------------------------------------------------------- #
io.txt:
    title:  Time Series for {}

    # columns [name, unit, description]
    columns:
        index: 
            [Time, '', Time stamp]
            # [sidt, h  Sidereal time in seconds since midnight]
        value: 
            [x, '', Data value]
        sigma:   
            [σ, '', Standard deviation uncertainty of data value]
        outlier: 
            [oflag, '', Outlier flag]

    precision:  5   # significant figures


# ---------------------------------------------------------------------------- #
ts:
    # time series plot parameters
    plotting:
        timescale:    s
        start:        null

        figure:
            size:           [14, 8]
            margins:
                top:        0.81
                bottom:     0.1
                left:       0.065
                right:      0.94

        axes:
            plims:          [-0.1, 99.99]
            labels:
                # TODO: axes_label_position: (left right center <>^)
                x:
                    top:        Time (UTC)
                    bottom:     Δt (s)
                    pad:        -17.5
                    ticks:
                        rotation:   45
                y:
                    left:       Relative Flux

            twinx:        null  # Top x-axis display format

        line:
            ls:             '-'
            ms:             0

        errorbar:
            fmt:            o
            ms:             2.5
            mec:            none
            capsize:        0
            elinewidth:     0.5
        
        spans:
            label:          filtered
            alpha:          0.2
            color:          r
        
        hist:
            bins:           50
            alpha:          0.75
            # color:        b
            orientation:    horizontal
        
        legend:
            loc:            upper right  # TODO: option for no legend
            fancybox:       True
            framealpha:     0.25
            numpoints:      1
            markerscale:    3

# ---------------------------------------------------------------------------- #
spectral:
    io.txt:
        title:  Spectral density estimate for {}

        # columns [name, unit, description]
        columns:
            time: 
                [Frq, 'Hz', Frequency]
            value: 
                [Power, '', Power]

        precision:  3   # significant figures

    tfr:
        ts: 
            color:  g
            ms:     1.5

            axes:
                x:
                    ticks:
                        which:          both
                        top:            True
                        labeltop:       True
                        labelbottom:    False
                        direction:      inout
                        pad:            0
                y:  
                    label:              Signal
                    ticks:
                        which:          both
                        right:          True
                        direction:      inout

        sde:
            color: 'g'
            color_cycle:    [c, b, m, g, y, orange]

            axes:
                ticks:
                    which:          both
                    left:           False
                    labelleft:      False
                    right:          True
                    bottom:         False
                    labelbottom:    False  # cbar gets these
                    top:            True
                    direction:      inout

                x:
                    label:          Time (s)
                y:
                    label:          Frequency (Hz)

                twin:
                    y:
                        label:
                            text:   Period (s)
                            pad:    50
                        ticks:    
                            left:       False
                            labelleft:  False
                            right:      False
                
        hatch:  
            facecolor:  none
            edgecolor:  r
            alpha:      0.65
            linewidth:  1
            hatch:      //

        hover:
            color:          r
            ts:   
                alpha:      0.35
            map:  
                lw:         1
                ls:         --
            sde:
                alpha:      0.65
                lw:         1.5

        figure:
            size:           [11, 6.53]

            margins:
                hspace:     0.02
                wspace:     0.005
                top:        0.925
                bottom:     0.08
                left:       0.05
                right:      0.915  # space for cbar ticks